. $PSScriptRoot/Enable-SQLManagedBackup.ps1
. $PSScriptRoot/Disable-SQLManagedBackup.ps1
. $PSScriptRoot/Get-NonAGDatabases.ps1
. $PSScriptRoot/Get-AGDatabases.ps1
. $PSScriptRoot/Get-AGServerInstances.ps1
. $PSScriptRoot/Get-ManagedBackupConfig.ps1
. $PSScriptRoot/Set-ManagedBackupCredential.ps1
. $PSScriptRoot/Get-SharedAccessSignature.ps1
. $PSScriptRoot/Get-StorageContext.ps1
. $PSScriptRoot/Remove-Blob.ps1
. $PSScriptRoot/Get-CorruptedBackupBlobs.ps1